language: java
jdk:
- oraclejdk11
script:
- "./mvnw clean verify"
branches:
  only:
  - main
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: shilen-money-transfer-api
  on:
    repo: gtekle / shilen-money-transfer-api
    branch: main
  skip_cleanup: 'true'