spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-216-185-51.eu-west-1.compute.amazonaws.com:5432/da980pqrbpdq82?ssl=true&sslmode=require
    username: afqicpjnrbusvo
    password: d11f05edaa87d7b971601327c58c1825127b76b24fb81fd62c3bc6f80891bd98
    # In Spring boot 2, database initialization only works for embedded databases (H2, HSQLDB).
    # If you want to use it for other databases, you need to change the
    initialization-mode: always
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

# https://www.baeldung.com/spring-boot-actuators
management.endpoints.web.exposure.include: '*'